spring:  
  datasource:
    url: jdbc:mysql://localhost:3306/jzy_cxkj
    username: root  
    password: 1234  
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  application:
    name: movie-controller
  cloud:
    refresh:
      refreshable: none
        
eureka:
  client:
    service-url:
       defaultZone: http://192.168.20.191:8761/eureka/
#      defaultZone: http://admin:123@192.168.20.191:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
mybatis:
  mapper-locations: classpath*:com/ly/*/mapper/*.xml
name: 正式